const promptRef = `sha256:${"c".repeat(64)}`;

export const observeGraphVisualFixture = {
  display: {
    graph: {
      run: {
        run_id: "run_fanout_resume_01",
        thread_id: "thread_9f31",
        title: "collector release gate",
        status: "active",
        started_at: "2026-07-28T12:00:00Z",
        latest_journal_sequence: "14",
        active_attempt_id: "attempt-2",
      },
      nodes: [
        {
          node_id: "run",
          kind: "run",
          label: "collector release gate",
          status: "active",
          started_at: "2026-07-28T12:00:00Z",
          duration_ms: 18420,
        },
        {
          node_id: "attempt:1",
          kind: "attempt",
          label: "attempt 1",
          status: "failed",
          attempt_id: "attempt-1",
          started_at: "2026-07-28T12:00:00Z",
          ended_at: "2026-07-28T12:00:11Z",
          duration_ms: 11000,
        },
        {
          node_id: "agent:contracts:1",
          kind: "agent",
          label: "contracts",
          status: "succeeded",
          attempt_id: "attempt-1",
          agent_id: "agent-contracts",
          started_at: "2026-07-28T12:00:01Z",
          ended_at: "2026-07-28T12:00:06Z",
          duration_ms: 5100,
        },
        {
          node_id: "agent:collector:1",
          kind: "agent",
          label: "collector journal",
          status: "failed",
          attempt_id: "attempt-1",
          agent_id: "agent-collector",
          started_at: "2026-07-28T12:00:01Z",
          ended_at: "2026-07-28T12:00:09Z",
          duration_ms: 7900,
          content_refs: [promptRef],
        },
        {
          node_id: "agent:mcp:1",
          kind: "agent",
          label: "mcp projection",
          status: "succeeded",
          attempt_id: "attempt-1",
          agent_id: "agent-mcp",
          started_at: "2026-07-28T12:00:01Z",
          ended_at: "2026-07-28T12:00:07Z",
          duration_ms: 6200,
        },
        {
          node_id: "gate:join:1",
          kind: "gate",
          label: "join / spec review",
          status: "failed",
          attempt_id: "attempt-1",
          started_at: "2026-07-28T12:00:09Z",
          ended_at: "2026-07-28T12:00:11Z",
          duration_ms: 1800,
        },
        {
          node_id: "attempt:2",
          kind: "attempt",
          label: "attempt 2 · resume",
          status: "running",
          attempt_id: "attempt-2",
          started_at: "2026-07-28T12:00:12Z",
          duration_ms: 6420,
        },
        {
          node_id: "agent:collector:2",
          kind: "agent",
          label: "collector journal",
          status: "succeeded",
          attempt_id: "attempt-2",
          agent_id: "agent-collector",
          started_at: "2026-07-28T12:00:12Z",
          ended_at: "2026-07-28T12:00:17Z",
          duration_ms: 4980,
        },
        {
          node_id: "tool:test",
          kind: "tool_call",
          label: "dotnet test · workflow",
          status: "succeeded",
          attempt_id: "attempt-2",
          agent_id: "agent-collector",
          started_at: "2026-07-28T12:00:17Z",
          ended_at: "2026-07-28T12:00:18Z",
          duration_ms: 1120,
        },
        {
          node_id: "gate:release",
          kind: "gate",
          label: "release evidence",
          status: "running",
          attempt_id: "attempt-2",
          started_at: "2026-07-28T12:00:18Z",
          duration_ms: 320,
        },
      ],
      edges: [
        {
          edge_id: "run-attempt-1",
          source_node_id: "run",
          target_node_id: "attempt:1",
          kind: "control",
          provenance: { type: "recorded", event_ids: ["evt-01"] },
        },
        {
          edge_id: "attempt-contracts",
          source_node_id: "attempt:1",
          target_node_id: "agent:contracts:1",
          kind: "control",
          provenance: { type: "recorded", event_ids: ["evt-02"] },
        },
        {
          edge_id: "attempt-collector",
          source_node_id: "attempt:1",
          target_node_id: "agent:collector:1",
          kind: "control",
          provenance: { type: "recorded", event_ids: ["evt-03"] },
        },
        {
          edge_id: "attempt-mcp",
          source_node_id: "attempt:1",
          target_node_id: "agent:mcp:1",
          kind: "control",
          provenance: { type: "recorded", event_ids: ["evt-04"] },
        },
        {
          edge_id: "contracts-join",
          source_node_id: "agent:contracts:1",
          target_node_id: "gate:join:1",
          kind: "gate",
          provenance: { type: "recorded", event_ids: ["evt-06"] },
        },
        {
          edge_id: "collector-join",
          source_node_id: "agent:collector:1",
          target_node_id: "gate:join:1",
          kind: "gate",
          provenance: { type: "recorded", event_ids: ["evt-08"] },
        },
        {
          edge_id: "mcp-join",
          source_node_id: "agent:mcp:1",
          target_node_id: "gate:join:1",
          kind: "gate",
          provenance: { type: "recorded", event_ids: ["evt-07"] },
        },
        {
          edge_id: "write-conflict",
          source_node_id: "agent:collector:1",
          target_node_id: "agent:mcp:1",
          kind: "conflict",
          provenance: {
            type: "derived",
            event_ids: ["evt-write-a", "evt-write-b"],
            evidence: "overlapping writes to server/src/contract-validation.ts",
            confidence: 0.94,
          },
        },
        {
          edge_id: "interrupt-resume",
          source_node_id: "gate:join:1",
          target_node_id: "attempt:2",
          kind: "temporal",
          provenance: { type: "recorded", event_ids: ["evt-10", "evt-11"] },
        },
        {
          edge_id: "resume-collector",
          source_node_id: "attempt:2",
          target_node_id: "agent:collector:2",
          kind: "control",
          provenance: { type: "recorded", event_ids: ["evt-12"] },
        },
        {
          edge_id: "collector-test",
          source_node_id: "agent:collector:2",
          target_node_id: "tool:test",
          kind: "resource",
          provenance: { type: "recorded", event_ids: ["evt-13"] },
        },
        {
          edge_id: "test-release",
          source_node_id: "tool:test",
          target_node_id: "gate:release",
          kind: "gate",
          provenance: { type: "recorded", event_ids: ["evt-14"] },
        },
      ],
      statistics: {
        t1_ms: 34840,
        t_infinity_ms: 18420,
        wall_time_ms: 18420,
        peak_concurrency: 3,
        worker_count: 3,
        parallel_lower_bound_ms: 18420,
        critical_path_node_ids: [
          "run",
          "attempt:1",
          "agent:collector:1",
          "gate:join:1",
          "attempt:2",
          "agent:collector:2",
          "tool:test",
          "gate:release",
        ],
      },
      journal_sequence: "14",
      has_more_nodes: false,
      has_more_edges: false,
      total_node_count: 10,
      total_edge_count: 12,
    },
    live_controls_available: true,
    mode: "live",
  },
  updates: {
    page: {
      events: [
        event("evt-01", "1", "attempt_started", { attempt_id: "attempt-1" }),
        event("evt-02", "2", "agent_spawned", { agent_id: "agent-contracts" }),
        event("evt-03", "3", "agent_spawned", { agent_id: "agent-collector" }),
        event("evt-04", "4", "agent_spawned", { agent_id: "agent-mcp" }),
        event("evt-06", "6", "agent_completed", { agent_id: "agent-contracts" }),
        event("evt-07", "7", "agent_completed", { agent_id: "agent-mcp" }),
        event("evt-08", "8", "agent_completed", { agent_id: "agent-collector" }),
        event("evt-09", "9", "attempt_completed", { attempt_id: "attempt-1" }),
        event("evt-10", "10", "control_applied", {}),
        event("evt-11", "11", "thread_resumed", { attempt_id: "attempt-2" }),
        event("evt-12", "12", "agent_started", {
          agent_id: "agent-collector",
          attempt_id: "attempt-2",
        }),
        event("evt-13", "13", "tool_completed", {
          agent_id: "agent-collector",
          attempt_id: "attempt-2",
          tool_call_id: "tool-test",
        }),
        event("evt-14", "14", "wait_started", { attempt_id: "attempt-2" }),
      ],
      next_sequence: "14",
      high_water_mark: "14",
      cursor_gap: false,
    },
    content: {
      content_ref: promptRef,
      content_type: "text/plain",
      encoding: "utf8",
      content:
        "Investigate the projection mismatch. Preserve attempt one as failed, resume the same thread, and prove the rebuilt graph converges.",
      size_bytes: 128,
    },
    mode: "live",
  },
} as const;

function event(
  eventId: string,
  sequence: string,
  kind: string,
  identities: Record<string, string>,
) {
  return {
    event_id: eventId,
    source_sequence: sequence,
    timestamp: `2026-07-28T12:00:${sequence.padStart(2, "0")}Z`,
    kind,
    run_id: "run_fanout_resume_01",
    client_id: "qyl-codex",
    journal_sequence: sequence,
    ...identities,
  };
}
