import { CallToolRequestSchema, CallToolResultSchema } from "@modelcontextprotocol/core";
import { ProtocolError } from "@modelcontextprotocol/server";
import type { McpServer, CallToolRequest, CallToolResult, ServerContext } from "@modelcontextprotocol/server";
import { randomUUID } from "node:crypto";
import { rename } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import { z } from "zod";
import { AtomicJsonStore, PersistenceError } from "./atomic-json-store.js";
import type {
  McpPropagationCarrier,
  McpTelemetryTransport,
} from "./mcp-semconv.js";
import { SecretRedactor } from "./secret-redactor.js";
import {
  McpTelemetry,
  type ActiveMcpOperation,
} from "./telemetry.js";

// 3: operation metadata only. Known older layouts are projected into this
// schema and replaced atomically, without keeping an archive of their payloads.
const NATIVE_STATE_VERSION = 3 as const;
const DEFAULT_MAX_EXECUTIONS = 1_000;
const NATIVE_SERVER_ID = "qyl.mcp/native";

const IdentifierSchema = z.string().min(1).max(256);
const IsoDateSchema = z.iso.datetime({ offset: true });
const NativeExecutionRecordSchema = z.object({
  // Generated by this server; never a client-provided JSON-RPC request id.
  id: IdentifierSchema,
  toolName: z.string().min(1).max(1_024),
  status: z.enum(["running", "succeeded", "failed"]),
  createdAt: IsoDateSchema,
  startedAt: IsoDateSchema,
  completedAt: IsoDateSchema.optional(),
  durationMs: z.number().finite().nonnegative().optional(),
  errorType: z.string().min(1).max(128).optional(),
}).strict();
const NativeExecutionStateSchema = z.object({
  version: z.literal(NATIVE_STATE_VERSION),
  executions: z.array(NativeExecutionRecordSchema),
}).strict();

// Strip unknown fields before migration: legacy request/result contents must
// never reach a new write, even when an old file contains unrecognized fields.
const LegacyNativeExecutionStateSchema = z.object({
  version: z.union([z.literal(1), z.literal(2)]),
  executions: z.array(NativeExecutionRecordSchema.omit({ toolName: true, errorType: true })
    .extend({
      request: z.object({ toolName: NativeExecutionRecordSchema.shape.toolName }),
      error: z.object({ code: NativeExecutionRecordSchema.shape.errorType }).optional(),
    }).strip()),
}).strict();

export type NativeExecutionRecord = z.infer<typeof NativeExecutionRecordSchema>;
interface NativeExecutionState {
  version: typeof NATIVE_STATE_VERSION;
  executions: NativeExecutionRecord[];
}

export interface NativeExecutionRepository {
  save(record: NativeExecutionRecord): Promise<void>;
}

export interface FileNativeExecutionRepositoryOptions {
  filePath?: string;
  maxExecutions?: number;
  now?: () => number;
  redactor?: SecretRedactor;
  environment?: Readonly<Record<string, string | undefined>>;
}

/** Bounded operation metadata kept separately from Workbench execution state. */
export class FileNativeExecutionRepository implements NativeExecutionRepository {
  private store: AtomicJsonStore<NativeExecutionState>;
  private readonly openStore: () => AtomicJsonStore<NativeExecutionState>;
  private readonly filePath: string;
  private readonly maxExecutions: number;
  private readonly now: () => number;
  private initialization: Promise<void> | undefined;
  private needsMigration = false;

  constructor(options: FileNativeExecutionRepositoryOptions = {}) {
    const environment = options.environment ?? process.env;
    const redactor = options.redactor ?? new SecretRedactor({
      environment,
    });
    this.maxExecutions = positiveInteger(
      options.maxExecutions ?? DEFAULT_MAX_EXECUTIONS,
      "maxExecutions",
    );
    this.now = options.now ?? Date.now;
    this.filePath = options.filePath ?? nativeStatePath(environment);
    this.openStore = () =>
      new AtomicJsonStore(this.filePath, {
        initial: () => ({ version: NATIVE_STATE_VERSION, executions: [] }),
        parse: (value) => {
          const legacy = LegacyNativeExecutionStateSchema.safeParse(value);
          if (!legacy.success) return NativeExecutionStateSchema.parse(value);
          this.needsMigration = true;
          return NativeExecutionStateSchema.parse({
            version: NATIVE_STATE_VERSION,
            executions: legacy.data.executions.map(({ request, error, ...record }) => ({
              ...record,
              toolName: request.toolName,
              ...(error?.code === undefined ? {} : { errorType: error.code }),
            })),
          });
        },
        prepareForWrite: (value) =>
          NativeExecutionStateSchema.parse(redactor.redact(value)),
      });
    this.store = this.openStore();
  }

  /**
   * Move a state file this build cannot read out of the way, and say so.
   *
   * The schema deliberately refuses to guess an unknown layout, but refusing
   * forever is not the same as refusing to guess: a state file written before a
   * version bump would otherwise fail every single tool call for the life of the
   * installation, because the store caches its failed load and evidence is
   * written before the tool runs. Renaming preserves the old records for anyone
   * who wants them and lets this process start a fresh log. Known version-1/2
   * files follow the payload-removing migration instead of this recovery path.
   */
  private async archiveUnreadableState(reason: PersistenceError): Promise<void> {
    const archived = `${this.filePath}.unreadable-${new Date(this.now()).toISOString().replaceAll(":", "-")}`;
    await rename(this.filePath, archived);
    console.error(
      `qyl.mcp could not read its execution evidence (${reason.kind}); ` +
        `moved it to ${archived} and started a new log`,
    );
  }

  async save(record: NativeExecutionRecord): Promise<void> {
    await this.initialize();
    const validated = NativeExecutionRecordSchema.parse(record);
    await this.store.transact((state) => {
      const index = state.executions.findIndex((entry) => entry.id === validated.id);
      if (index < 0) state.executions.push(validated);
      else state.executions[index] = validated;
      state.executions.sort((left, right) => left.createdAt.localeCompare(right.createdAt));
      if (state.executions.length > this.maxExecutions) {
        state.executions.splice(0, state.executions.length - this.maxExecutions);
      }
    });
  }

  async list(): Promise<NativeExecutionRecord[]> {
    await this.initialize();
    return (await this.store.read()).executions;
  }

  private initialize(): Promise<void> {
    this.initialization ??= this.initializeCore();
    return this.initialization;
  }

  private async initializeCore(): Promise<void> {
    try {
      await this.store.initialize();
    } catch (error) {
      // A write fault is about this filesystem, not about the file's contents;
      // archiving would not help and would discard readable evidence.
      if (!(error instanceof PersistenceError) || error.kind === "write_failed") throw error;
      await this.archiveUnreadableState(error);
      this.store = this.openStore();
      await this.store.initialize();
    }
    if (this.needsMigration) {
      await this.store.replace(await this.store.read());
      this.needsMigration = false;
    }
    const completedMs = this.now();
    const completedAt = timestamp(completedMs);
    const current = await this.store.read();
    if (!current.executions.some((record) => record.status === "running")) return;
    await this.store.transact((state) => {
      for (const record of state.executions) {
        if (record.status !== "running") continue;
        record.status = "failed";
        record.completedAt = completedAt;
        record.durationMs = Math.max(0, completedMs - Date.parse(record.startedAt));
        record.errorType = "process_interrupted";
      }
    });
  }
}

export interface NativeExecutionTelemetry {
  startOperation: McpTelemetry["startOperation"];
  close?(): Promise<void>;
}

export interface NativeExecutionRuntimeOptions {
  telemetry?: NativeExecutionTelemetry;
  redactor?: SecretRedactor;
  now?: () => number;
  id?: () => string;
}

export interface NativeToolCallInput {
  request: CallToolRequest;
  ctx: ServerContext;
  transport: McpTelemetryTransport;
}

/** Owns the automatic inbound tools/call lifecycle and evidence transaction. */
export class NativeExecutionRuntime {
  private readonly telemetry?: NativeExecutionTelemetry;
  private readonly redactor: SecretRedactor;
  private readonly now: () => number;
  private readonly id: () => string;

  constructor(
    private readonly repository: NativeExecutionRepository,
    options: NativeExecutionRuntimeOptions = {},
  ) {
    this.telemetry = options.telemetry;
    this.redactor = options.redactor ?? new SecretRedactor({
      environment: process.env,
    });
    this.now = options.now ?? Date.now;
    this.id = options.id ?? randomUUID;
  }

  async execute(
    input: NativeToolCallInput,
    invoke: () => unknown,
  ): Promise<CallToolResult> {
    const startedMs = this.now();
    const executionId = this.id();
    const startedAt = timestamp(startedMs);
    const toolName = input.request.params.name;
    const operation = this.startTelemetry(input, executionId, startedMs);
    const running = NativeExecutionRecordSchema.parse({
      id: executionId,
      toolName: this.redactor.redactText(toolName).slice(0, 1_024),
      status: "running",
      createdAt: startedAt,
      startedAt,
    });

    try {
      await this.repository.save(running);
    } catch (error) {
      operation?.end({
        endTimeMs: this.now(),
        errorType: "evidence_persistence_failed",
      });
      throw new EvidenceRecordingError(error);
    }

    let result: CallToolResult;
    try {
      const rawResult = await (operation?.run(invoke) ?? invoke());
      result = CallToolResultSchema.parse(rawResult);
    } catch (error) {
      const completedMs = this.now();
      const completedAt = timestamp(completedMs);
      const failedRecord = NativeExecutionRecordSchema.parse({
        ...running,
        status: "failed",
        completedAt,
        durationMs: duration(startedMs, completedMs),
        errorType: errorType(error),
      });
      try {
        await this.repository.save(failedRecord);
      } catch (persistenceError) {
        operation?.end({
          endTimeMs: this.now(),
          errorType: "evidence_persistence_failed",
        });
        throw new EvidenceRecordingError(persistenceError);
      }
      operation?.end({
        endTimeMs: completedMs,
        errorType: errorType(error),
        ...(error instanceof ProtocolError
          ? { rpcResponseStatusCode: String(error.code) }
          : {}),
      });
      throw error;
    }

    const completedMs = this.now();
    const completedAt = timestamp(completedMs);
    const toolFailed = result.isError === true;
    const completedRecord = NativeExecutionRecordSchema.parse({
      ...running,
      status: toolFailed ? "failed" : "succeeded",
      completedAt,
      durationMs: duration(startedMs, completedMs),
      ...(toolFailed ? { errorType: "tool_result_error" } : {}),
    });
    try {
      await this.repository.save(completedRecord);
    } catch (error) {
      operation?.end({
        endTimeMs: this.now(),
        errorType: "evidence_persistence_failed",
      });
      throw new EvidenceRecordingError(error);
    }
    operation?.end({
      endTimeMs: completedMs,
      ...(toolFailed ? { errorType: "tool_error" } : {}),
    });
    return result;
  }

  close(): Promise<void> {
    return this.telemetry?.close?.() ?? Promise.resolve();
  }

  get telemetryEnabled(): boolean {
    return this.telemetry !== undefined;
  }

  private startTelemetry(
    input: NativeToolCallInput,
    executionId: string,
    startedMs: number,
  ): ActiveMcpOperation | undefined {
    try {
      return this.telemetry?.startOperation({
        role: "server",
        method: "tools/call",
        serverId: NATIVE_SERVER_ID,
        toolName: input.request.params.name,
        transport: input.transport,
        jsonRpcProtocolVersion: "2.0",
        executionId,
        remotePropagation: propagationCarrier(input.request.params._meta),
        startTimeMs: startedMs,
      });
    } catch {
      return undefined;
    }
  }
}

type UntypedRequestHandler = (
  request: unknown,
  ctx: ServerContext,
) => unknown;
type UntypedSetRequestHandler = (
  method: string,
  handlerOrSchemas: unknown,
  handler?: UntypedRequestHandler,
) => void;
/**
 * A fault in the evidence layer itself, as opposed to anything the tool did.
 * Only these become an isError result; a malformed tool result is a server bug
 * that fails the runtime's CallToolResultSchema parse and stays loud.
 */
export class EvidenceRecordingError extends Error {
  constructor(readonly cause: unknown) {
    super(cause instanceof Error ? cause.message : String(cause));
    this.name = "EvidenceRecordingError";
  }
}

/**
 * Report a recording-layer fault to the caller of `tools/call`.
 *
 * The detail goes to stderr rather than into the result: the message reaches a
 * model, and a persistence fault names a local state path that has no meaning
 * to it and does not belong on the wire.
 */
function recordingFailureResult(error: unknown): CallToolResult {
  const detail = error instanceof Error ? error.message : String(error);
  console.error(`native execution evidence could not be recorded: ${detail}`);
  return {
    content: [{
      type: "text",
      text: "This tool call was not run: qyl.mcp could not record its execution evidence. " +
        "The server logged the reason; every tool stays unavailable until it is resolved.",
    }],
    isError: true,
  };
}

const instrumentedServers = new WeakSet<McpServer>();
const nativeTelemetryServers = new WeakSet<McpServer>();
const recordingServers = new WeakSet<McpServer>();

/** Wrap the SDK's single tools/call dispatcher, covering all current and future tools. */
export function installNativeExecutionRecording(
  server: McpServer,
  runtime: NativeExecutionRuntime,
  transport: McpTelemetryTransport,
): void {
  if (instrumentedServers.has(server)) return;
  instrumentedServers.add(server);
  if (runtime.telemetryEnabled) nativeTelemetryServers.add(server);
  const lowLevel = server.server as unknown as { setRequestHandler: UntypedSetRequestHandler };
  const original = lowLevel.setRequestHandler.bind(server.server);
  lowLevel.setRequestHandler = (method, handlerOrSchemas, customHandler) => {
    const handler = customHandler ?? handlerOrSchemas;
    if (method !== "tools/call" || typeof handler !== "function") {
      original(method, handlerOrSchemas, customHandler);
      return;
    }
    recordingServers.add(server);
    original(method, async (request: unknown, ctx: ServerContext) => {
      const validated = CallToolRequestSchema.parse(request);
      try {
        return await runtime.execute(
          { request: validated, ctx, transport },
          () => handler(validated, ctx),
        );
      } catch (error) {
        // The SDK converts throws into isError only inside the dispatcher this
        // wrapper calls (errors.md); above it a throw leaves as a JSON-RPC error,
        // so an evidence fault is answered here and every other throw passes.
        if (!(error instanceof EvidenceRecordingError)) throw error;
        return recordingFailureResult(error.cause);
      }
    });
  };
}

/**
 * Fail construction when recording never took hold, which is otherwise silent.
 *
 * The wrapper above only sees a tools/call registration that happens after it is
 * installed. McpServer registers that dispatcher in its own constructor as soon as
 * `capabilities.tools` is declared there, and only defers it to the first
 * registerTool call when it is not — so declaring the capability up front would
 * leave every tool call unrecorded while answering normally. Evidence is an audit
 * surface; losing it has to be an error at startup, not a gap discovered later.
 */
export function assertNativeExecutionRecordingArmed(server: McpServer): void {
  if (recordingServers.has(server)) return;
  throw new Error(
    "native execution recording never wrapped a tools/call dispatcher: the MCP server " +
      "registered it before installNativeExecutionRecording ran (declaring capabilities.tools " +
      "on the McpServer constructor does this). Register tools after installing recording.",
  );
}

export function hasNativeExecutionTelemetry(server: unknown): boolean {
  return typeof server === "object" &&
    server !== null &&
    nativeTelemetryServers.has(server as McpServer);
}

let defaultRuntime: NativeExecutionRuntime | undefined;

export function defaultNativeExecutionRuntime(
  environment: Readonly<Record<string, string | undefined>> = process.env,
): NativeExecutionRuntime {
  defaultRuntime ??= createDefaultRuntime(environment);
  return defaultRuntime;
}

export async function closeDefaultNativeExecutionRuntime(): Promise<void> {
  const runtime = defaultRuntime;
  defaultRuntime = undefined;
  await runtime?.close();
}

function createDefaultRuntime(
  environment: Readonly<Record<string, string | undefined>>,
): NativeExecutionRuntime {
  const redactor = new SecretRedactor({
    environment,
  });
  const repository = new FileNativeExecutionRepository({ environment, redactor });
  let telemetry: McpTelemetry | undefined;
  try {
    telemetry = new McpTelemetry(environment, redactor);
  } catch {
    telemetry = undefined;
  }
  return new NativeExecutionRuntime(repository, { redactor, telemetry });
}

function nativeStatePath(environment: Readonly<Record<string, string | undefined>>): string {
  return environment.QYL_MCP_NATIVE_STATE_PATH
    ?? join(homedir(), ".qyl", "mcp-native-executions.json");
}

function errorType(error: unknown): string {
  if (error instanceof ProtocolError) return `mcp_${error.code}`;
  if (error instanceof Error && /^[A-Za-z][A-Za-z0-9]*$/u.test(error.name)) {
    return error.name.slice(0, 128);
  }
  return "native_tool_failure";
}

function propagationCarrier(value: unknown): McpPropagationCarrier | undefined {
  if (!isRecord(value)) return undefined;
  // Preserve trace parenting without passing arbitrary metadata or baggage to
  // logging/exporters. OpenTelemetry validates the trace/span IDs on extraction.
  const traceparent = value.traceparent;
  return typeof traceparent === "string"
    && /^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$/u.test(traceparent)
    ? { traceparent }
    : undefined;
}

function duration(startedMs: number, completedMs: number): number {
  return Math.max(0, completedMs - startedMs);
}

function timestamp(value: number): string {
  return new Date(value).toISOString();
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function positiveInteger(value: number, name: string): number {
  if (!Number.isSafeInteger(value) || value <= 0) {
    throw new Error(`${name} must be a positive integer.`);
  }
  return value;
}
